services:
  # Main application service
  assetdex:
    build: .
    ports:
      - "3001:80"
    environment:
      - VITE_SUPABASE_URL=http://kong:8000
      - VITE_SUPABASE_ANON_KEY=${ANON_KEY}
      - SUPABASE_URL=http://kong:8000
      - SUPABASE_ANON_KEY=${ANON_KEY}
      - NODE_ENV=development
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.env.local:/app/.env.local:ro
    networks:
      - supabase_default
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      db-schema-initiator:
        condition: service_completed_successfully

  # Database schema initializer (runs once and exits)
  db-schema-initiator:
    image: postgres:15-alpine
    working_dir: /app
    environment:
      POSTGRES_HOST: supabase-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - ./scripts:/app/scripts:ro
      - ./database:/app/database:ro
    networks:
      - supabase_default
    entrypoint: ["/bin/sh", "-exc", "
      echo '=== Starting migration ===' && \
      echo 'Current directory:' && pwd && ls -la && \
      echo 'Scripts directory:' && ls -la /app/scripts/ && \
      echo 'Database directory:' && ls -la /app/database/ && \
      echo 'Waiting for database to be ready...' && \
      until pg_isready -h supabase-db -p 5432 -U postgres; do sleep 1; done && \
      echo 'Database is ready, running migration...' && \
      cd /app && \
      sh /app/scripts/run-migration.sh
    "]

# Network configuration
networks:
  supabase_default:
    external: true
