version: '3.8'

services:
  assetdex:
    build: .
    ports:
      - "3000:80"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./scripts/run-migration.sh:/app/scripts/run-migration.sh:ro
      - ./database/consolidated-migration.sql:/app/database/consolidated-migration.sql:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: ["sh", "-c", "npm run dev 
/app/scripts/run-migration.sh"]

  # Optional: Add Supabase local development stack
  # Uncomment the following if you want to run Supabase locally
  # supabase:
  #   image: supabase/supabase:latest
  #   ports:
  #     - "54321:54321"
  #   environment:
  #     - POSTGRES_PASSWORD=your-super-secret-and-long-postgres-password
  #   volumes:
  #     - ./supabase:/docker-entrypoint-initdb.d