# Enable CORS
[functions.get-default-rack]
  cors = true
  verify_jwt = false
  allowed_origins = ["*"]
  allowed_headers = ["Authorization", "Content-Type", "apikey", "x-client-info"]
  allowed_methods = ["GET", "POST", "OPTIONS"]
