
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itsfttssdecjuyxrqgro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0c2Z0dHNzZGVjanV5eHJxZ3JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDkzODMsImV4cCI6MjA2NzI4NTM4M30.fROnRK8cKr7JXRRBAyIWlbpitvsfYGrVw_bN_DSW5Vk";

console.log('Supabase URL:', SUPABASE_URL);
console.log('Supabase Key:', SUPABASE_PUBLISHABLE_KEY.substring(0, 20) + '...');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
